-- CANONICAL match_chunks — exported verbatim from the PRODUCTION database, 2026-07-29.
--
-- WHY THIS FILE EXISTS. The checked-in definition in supabase/migration_v2_rag.sql was four parameters
-- and four return columns behind what was actually running. The live function had been altered
-- out-of-band and never committed, so the repository described a ranker that had not existed for some
-- time. Anyone reading migration_v2_rag.sql to answer "how are sources ranked?" got the wrong answer.
--
-- THIS FILE IS NOW THE REFERENCE. It was produced by pg_get_functiondef against the live catalog, not by
-- hand-editing the old file to guess at the difference. test_schema_types.mjs derives its ground truth
-- from here. Do not edit this file to express an intended change: change the database, re-export, and
-- commit the export — otherwise the repo starts lying again in the other direction.
--
--   psql "$DATABASE_URL" -At -c \
--     "select pg_get_functiondef(p.oid) from pg_proc p
--        join pg_namespace n on n.oid = p.pronamespace
--       where n.nspname='public' and p.proname='match_chunks';"
--
-- WHAT THE DRIFT ADDED, and why it matters beyond bookkeeping:
--
--   parameters  rcr_weight (0.02), landmark_boost (0.05), max_journal_rank (2), elite_journal_boost (0.06)
--   columns     rcr, citation_count, is_landmark_trial, journal_rank
--
-- The Worker sends only the original six parameters by name, so those four run at these defaults on every
-- production request. Two consequences that were invisible from the repo:
--
--   1. ranked_score is NOT similarity. It is similarity plus four authority boosts (tier, landmark,
--      elite-journal, RCR). Any code that replaces ranked_score ordering with raw cosine is not
--      "reranking" — it is also silently repealing the authority policy. That is exactly the confound
--      Codex caught in the four-arm experiment on 2026-07-29.
--   2. `d.journal_rank <= max_journal_rank` is a HARD FILTER in the WHERE clause, not a boost. With the
--      default of 2, the 156 documents at journal_rank > 2 are unreachable by ANY retrieval request the
--      app makes — 6% of a 2,593-document corpus, excluded by a parameter named nowhere in the codebase.
--      Nothing currently overrides it. (Checked 2026-07-29: no document has a NULL journal_rank, so the
--      NULL-comparison trap — where `null <= 2` is null and the row silently drops — is not firing. It
--      would if the ingesters ever admitted one.)
--
-- The RCR term is capped: least(rcr_weight * ln(1 + rcr), 0.10), and applies only when rcr > 1. At the
-- default weight a paper needs an RCR near 150 to reach that cap, so in practice the term is small.

CREATE OR REPLACE FUNCTION public.match_chunks(
  query_embedding vector,
  match_count integer DEFAULT 10,
  min_similarity double precision DEFAULT 0.0,
  max_age_years integer DEFAULT NULL::integer,
  allowed_sources text[] DEFAULT NULL::text[],
  tier_boost_weight double precision DEFAULT 0.05,
  rcr_weight double precision DEFAULT 0.02,
  landmark_boost double precision DEFAULT 0.05,
  max_journal_rank smallint DEFAULT 2,
  elite_journal_boost double precision DEFAULT 0.06
)
RETURNS TABLE(
  chunk_id bigint,
  document_id uuid,
  chunk_index integer,
  section text,
  text text,
  tokens integer,
  similarity double precision,
  ranked_score double precision,
  source text,
  source_tier smallint,
  title text,
  authors text,
  journal text,
  year integer,
  pmid text,
  pmcid text,
  doi text,
  url text,
  publication_type text,
  license text,
  rcr double precision,
  citation_count integer,
  is_landmark_trial boolean,
  journal_rank smallint
)
LANGUAGE sql
STABLE
AS $function$
  select
    c.id as chunk_id, c.document_id, c.chunk_index, c.section, c.text, c.tokens,
    1 - (c.embedding <=> query_embedding) as similarity,
    (1 - (c.embedding <=> query_embedding))
      + ((4 - d.source_tier) * tier_boost_weight)
      + (case when d.is_landmark_trial then landmark_boost else 0 end)
      + (case when d.journal_rank = 1 then elite_journal_boost else 0 end)
      + least(case when d.rcr is not null and d.rcr > 1 then rcr_weight * ln(1 + d.rcr) else 0 end, 0.10)
      as ranked_score,
    d.source, d.source_tier, d.title, d.authors, d.journal, d.year,
    d.pmid, d.pmcid, d.doi, d.url, d.publication_type, d.license,
    d.rcr, d.citation_count, d.is_landmark_trial, d.journal_rank
  from public.document_chunks c
  join public.documents d on d.id = c.document_id
  where c.embedding is not null
    and (1 - (c.embedding <=> query_embedding)) >= min_similarity
    and (max_age_years is null or d.year is null or d.year >= extract(year from now())::int - max_age_years)
    and (allowed_sources is null or d.source = any(allowed_sources))
    and d.journal_rank <= max_journal_rank
  order by ranked_score desc
  limit match_count;
$function$;
